namespace TradingBrain.ConsoleApp;

public static class CleanNinjaScriptGenerator
{
    public static void GenerateAll(string outputDirectory)
    {
        Directory.CreateDirectory(outputDirectory);
        File.WriteAllText(
            Path.Combine(outputDirectory, "CleanNinjaBotIAReconstruction.cs"),
            Source);
    }

    private const string Source = """
// Clean-room reconstruction generated by TradingBrain.
// It is based on public metadata/defaults and offline behavior hypotheses.
// It does not reference or modify the protected vendor DLL.

using System;
using System.ComponentModel.DataAnnotations;
using NinjaTrader.Cbi;
using NinjaTrader.Data;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Indicators;

namespace NinjaTrader.NinjaScript.Strategies
{
    public class CleanNinjaBotIAVolatility : Strategy
    {
        private EMA ema1;
        private EMA ema2;
        private RSI rsi1;
        private ATR atr1;
        private SMA atrSma;
        private Series<double> atrSeries;
        private double sessionPv;
        private double sessionVolume;
        private DateTime sessionDate;
        private int longEntryBar = -1;
        private int shortEntryBar = -1;
        private double longEntryPrice;
        private double shortEntryPrice;
        private double highestProfit;

        [NinjaScriptProperty, Range(1, int.MaxValue)]
        [Display(Name = "contractSize", Order = 1, GroupName = "Parameters")]
        public int contractSize { get; set; }

        [NinjaScriptProperty, Range(0, 23)]
        [Display(Name = "SessionStartHour", Order = 2, GroupName = "Parameters")]
        public int SessionStartHour { get; set; }

        [NinjaScriptProperty, Range(0, 59)]
        [Display(Name = "SessionStartMinute", Order = 3, GroupName = "Parameters")]
        public int SessionStartMinute { get; set; }

        [NinjaScriptProperty, Range(0, 59)]
        [Display(Name = "SessionStartSecond", Order = 4, GroupName = "Parameters")]
        public int SessionStartSecond { get; set; }

        [NinjaScriptProperty, Range(0, 23)]
        [Display(Name = "SessionEndHour", Order = 5, GroupName = "Parameters")]
        public int SessionEndHour { get; set; }

        [NinjaScriptProperty, Range(0, 59)]
        [Display(Name = "SessionEndMinute", Order = 6, GroupName = "Parameters")]
        public int SessionEndMinute { get; set; }

        [NinjaScriptProperty, Range(0, 59)]
        [Display(Name = "SessionEndSecond", Order = 7, GroupName = "Parameters")]
        public int SessionEndSecond { get; set; }

        [NinjaScriptProperty, Range(1, int.MaxValue)]
        [Display(Name = "EMA1Period", Order = 8, GroupName = "Parameters")]
        public int EMA1Period { get; set; }

        [NinjaScriptProperty, Range(1, int.MaxValue)]
        [Display(Name = "EMA2Period", Order = 9, GroupName = "Parameters")]
        public int EMA2Period { get; set; }

        [NinjaScriptProperty, Range(1, int.MaxValue)]
        [Display(Name = "RSIPeriod", Order = 10, GroupName = "Parameters")]
        public int RSIPeriod { get; set; }

        [NinjaScriptProperty, Range(1, int.MaxValue)]
        [Display(Name = "RSISmooth", Order = 11, GroupName = "Parameters")]
        public int RSISmooth { get; set; }

        [NinjaScriptProperty, Range(1, int.MaxValue)]
        [Display(Name = "ATRPeriod", Order = 12, GroupName = "Parameters")]
        public int ATRPeriod { get; set; }

        [NinjaScriptProperty, Range(1, int.MaxValue)]
        [Display(Name = "ATRSMAPeriod", Order = 13, GroupName = "Parameters")]
        public int ATRSMAPeriod { get; set; }

        [NinjaScriptProperty, Range(1, int.MaxValue)]
        [Display(Name = "SMAVolumePeriod", Order = 14, GroupName = "Parameters")]
        public int SMAVolumePeriod { get; set; }

        [NinjaScriptProperty, Range(0.1, double.MaxValue)]
        [Display(Name = "TrailStopMultiplier", Order = 15, GroupName = "Parameters")]
        public double TrailStopMultiplier { get; set; }

        [NinjaScriptProperty, Range(0.1, double.MaxValue)]
        [Display(Name = "BreakEvenMultiplier", Order = 16, GroupName = "Parameters")]
        public double BreakEvenMultiplier { get; set; }

        [NinjaScriptProperty, Range(1, int.MaxValue)]
        [Display(Name = "TimeExitBars", Order = 17, GroupName = "Parameters")]
        public int TimeExitBars { get; set; }

        [NinjaScriptProperty, Range(1, int.MaxValue)]
        [Display(Name = "MaxDrawdown", Order = 18, GroupName = "Parameters")]
        public int MaxDrawdown { get; set; }

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Name = "CleanNinjaBotIAVolatility";
                Calculate = Calculate.OnBarClose;
                EntriesPerDirection = 1;
                EntryHandling = EntryHandling.AllEntries;
                IsExitOnSessionCloseStrategy = true;
                contractSize = 1;
                SessionStartHour = 9;
                SessionStartMinute = 30;
                SessionStartSecond = 0;
                SessionEndHour = 10;
                SessionEndMinute = 10;
                SessionEndSecond = 0;
                EMA1Period = 9;
                EMA2Period = 21;
                RSIPeriod = 14;
                RSISmooth = 3;
                ATRPeriod = 14;
                ATRSMAPeriod = 20;
                SMAVolumePeriod = 20;
                TrailStopMultiplier = 3.4;
                BreakEvenMultiplier = 0.4;
                TimeExitBars = 11;
                MaxDrawdown = 2;
            }
            else if (State == State.DataLoaded)
            {
                ema1 = EMA(EMA1Period);
                ema2 = EMA(EMA2Period);
                rsi1 = RSI(RSIPeriod, RSISmooth);
                atr1 = ATR(ATRPeriod);
                atrSeries = new Series<double>(this);
                atrSma = SMA(atrSeries, ATRSMAPeriod);
            }
        }

        protected override void OnBarUpdate()
        {
            if (CurrentBar < Math.Max(Math.Max(EMA2Period, RSIPeriod + RSISmooth), Math.Max(ATRPeriod + ATRSMAPeriod, SMAVolumePeriod)))
                return;

            ResetSessionVwapIfNeeded();
            var typical = (High[0] + Low[0] + Close[0]) / 3.0;
            sessionPv += typical * Volume[0];
            sessionVolume += Volume[0];
            var vwap = sessionVolume <= 0 ? Close[0] : sessionPv / sessionVolume;
            atrSeries[0] = atr1[0];

            if (!InTimeWindow(SessionStartHour, SessionStartMinute, SessionStartSecond, SessionEndHour, SessionEndMinute, SessionEndSecond))
            {
                if (Position.MarketPosition == MarketPosition.Long)
                    ExitLong("OutsideSession", "VolLong");
                else if (Position.MarketPosition == MarketPosition.Short)
                    ExitShort("OutsideSession", "VolShort");
                return;
            }

            var volSma = VolumeSma(SMAVolumePeriod);
            var volatilityOk = atr1[0] > atrSma[0] && Volume[0] > volSma * 1.2;
            var bullish = ema1[0] > ema2[0] && Close[0] > vwap && rsi1[0] >= 50;
            var bearish = ema1[0] < ema2[0] && Close[0] < vwap && rsi1[0] <= 50;

            if (Position.MarketPosition == MarketPosition.Flat)
            {
                highestProfit = 0;
                if (volatilityOk && bullish)
                {
                    longEntryBar = CurrentBar;
                    longEntryPrice = Close[0];
                    EnterLong(contractSize, "VolLong");
                }
                else if (volatilityOk && bearish)
                {
                    shortEntryBar = CurrentBar;
                    shortEntryPrice = Close[0];
                    EnterShort(contractSize, "VolShort");
                }
                return;
            }

            if (Position.MarketPosition == MarketPosition.Long)
            {
                var profit = Close[0] - longEntryPrice;
                highestProfit = Math.Max(highestProfit, profit);
                if (CurrentBar - longEntryBar >= TimeExitBars || profit <= -MaxDrawdown * TickSize || ema1[0] < ema2[0] || Close[0] < vwap)
                    ExitLong("VolExitLong", "VolLong");
                else
                    SetTrailStop("VolLong", CalculationMode.Price, Close[0] - atr1[0] * TrailStopMultiplier, false);
            }
            else if (Position.MarketPosition == MarketPosition.Short)
            {
                var profit = shortEntryPrice - Close[0];
                highestProfit = Math.Max(highestProfit, profit);
                if (CurrentBar - shortEntryBar >= TimeExitBars || profit <= -MaxDrawdown * TickSize || ema1[0] > ema2[0] || Close[0] > vwap)
                    ExitShort("VolExitShort", "VolShort");
                else
                    SetTrailStop("VolShort", CalculationMode.Price, Close[0] + atr1[0] * TrailStopMultiplier, false);
            }
        }

        private void ResetSessionVwapIfNeeded()
        {
            if (sessionDate == Time[0].Date)
                return;

            sessionDate = Time[0].Date;
            sessionPv = 0;
            sessionVolume = 0;
        }

        private double VolumeSma(int period)
        {
            var sum = 0.0;
            for (var i = 0; i < period; i++)
                sum += Volume[i];
            return sum / period;
        }

        private bool InTimeWindow(int sh, int sm, int ss, int eh, int em, int es)
        {
            var now = ToHHmmss(Time[0]);
            return now >= sh * 10000 + sm * 100 + ss && now <= eh * 10000 + em * 100 + es;
        }

        private static int ToHHmmss(DateTime time)
        {
            return time.Hour * 10000 + time.Minute * 100 + time.Second;
        }
    }

    public class CleanNinjaBotIATrend : Strategy
    {
        private ATR atr;
        private int trend;
        private int entryBar = -1;

        [NinjaScriptProperty, Range(1, int.MaxValue)]
        [Display(Name = "contractSize", Order = 1, GroupName = "Parameters")]
        public int contractSize { get; set; }

        [NinjaScriptProperty] public int StartHour { get; set; }
        [NinjaScriptProperty] public int StartMinute { get; set; }
        [NinjaScriptProperty] public int EndHour { get; set; }
        [NinjaScriptProperty] public int EndMinute { get; set; }
        [NinjaScriptProperty] public int Periods { get; set; }
        [NinjaScriptProperty] public double Multiplier { get; set; }
        [NinjaScriptProperty] public bool ChangeATR { get; set; }
        [NinjaScriptProperty] public int TargetTicks { get; set; }
        [NinjaScriptProperty] public int StopTicks { get; set; }
        [NinjaScriptProperty] public bool UseBreakEven { get; set; }
        [NinjaScriptProperty] public int BreakEvenTriggerTicks { get; set; }
        [NinjaScriptProperty] public int BreakEvenPlusTicks { get; set; }
        [NinjaScriptProperty] public bool UseTrailing { get; set; }
        [NinjaScriptProperty] public int TrailTriggerTicks { get; set; }
        [NinjaScriptProperty] public int TrailDistanceTicks { get; set; }

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Name = "CleanNinjaBotIATrend";
                Calculate = Calculate.OnBarClose;
                contractSize = 1;
                StartHour = 9;
                StartMinute = 30;
                EndHour = 14;
                EndMinute = 30;
                Periods = 10;
                Multiplier = 2;
                ChangeATR = true;
                TargetTicks = 305;
                StopTicks = 250;
                UseBreakEven = true;
                BreakEvenTriggerTicks = 60;
                BreakEvenPlusTicks = 5;
                UseTrailing = true;
                TrailTriggerTicks = 80;
                TrailDistanceTicks = 100;
            }
            else if (State == State.Configure)
            {
                SetProfitTarget(CalculationMode.Ticks, TargetTicks);
                SetStopLoss(CalculationMode.Ticks, StopTicks);
            }
            else if (State == State.DataLoaded)
            {
                atr = ATR(Periods);
            }
        }

        protected override void OnBarUpdate()
        {
            if (CurrentBar < Periods + 2)
                return;

            if (!InSession(StartHour, StartMinute, EndHour, EndMinute))
            {
                ExitIfOpen();
                return;
            }

            var highest = MAX(High, Periods)[0];
            var lowest = MIN(Low, Periods)[0];
            var mid = (highest + lowest) / 2.0;
            var upper = mid + atr[0] * Multiplier;
            var lower = mid - atr[0] * Multiplier;
            var newTrend = Close[0] > upper ? 1 : Close[0] < lower ? -1 : trend;
            var changed = newTrend != 0 && newTrend != trend;
            trend = newTrend;

            if (Position.MarketPosition == MarketPosition.Flat)
            {
                if (changed && trend > 0)
                {
                    entryBar = CurrentBar;
                    EnterLong(contractSize, "TrendLong");
                }
                else if (changed && trend < 0)
                {
                    entryBar = CurrentBar;
                    EnterShort(contractSize, "TrendShort");
                }
                return;
            }

            ManageOpenTrend();
            if (Position.MarketPosition == MarketPosition.Long && trend < 0)
                ExitLong("TrendFlipLong", "TrendLong");
            else if (Position.MarketPosition == MarketPosition.Short && trend > 0)
                ExitShort("TrendFlipShort", "TrendShort");
        }

        private void ManageOpenTrend()
        {
            var ticks = Position.MarketPosition == MarketPosition.Long
                ? (Close[0] - Position.AveragePrice) / TickSize
                : (Position.AveragePrice - Close[0]) / TickSize;

            if (UseBreakEven && ticks >= BreakEvenTriggerTicks)
            {
                var price = Position.MarketPosition == MarketPosition.Long
                    ? Position.AveragePrice + BreakEvenPlusTicks * TickSize
                    : Position.AveragePrice - BreakEvenPlusTicks * TickSize;
                SetStopLoss(CalculationMode.Price, price);
            }

            if (UseTrailing && ticks >= TrailTriggerTicks)
                SetTrailStop(CalculationMode.Ticks, TrailDistanceTicks);
        }

        private void ExitIfOpen()
        {
            if (Position.MarketPosition == MarketPosition.Long)
                ExitLong();
            else if (Position.MarketPosition == MarketPosition.Short)
                ExitShort();
        }

        private bool InSession(int sh, int sm, int eh, int em)
        {
            var now = Time[0].Hour * 10000 + Time[0].Minute * 100 + Time[0].Second;
            return now >= sh * 10000 + sm * 100 && now <= eh * 10000 + em * 100;
        }
    }

    public class CleanNinjaBotIAMomentum : Strategy
    {
        private MACD macdI;

        [NinjaScriptProperty] public int Quantity { get; set; }
        [NinjaScriptProperty] public int StartHour { get; set; }
        [NinjaScriptProperty] public int StartMinute { get; set; }
        [NinjaScriptProperty] public int EndHour { get; set; }
        [NinjaScriptProperty] public int EndMinute { get; set; }
        [NinjaScriptProperty] public int Lb { get; set; }
        [NinjaScriptProperty] public int MacdFast { get; set; }
        [NinjaScriptProperty] public int MacdSlow { get; set; }
        [NinjaScriptProperty] public int MacdSignal { get; set; }
        [NinjaScriptProperty] public int StopLossTicks { get; set; }
        [NinjaScriptProperty] public int ProfitTargetTicks { get; set; }
        [NinjaScriptProperty] public bool UseTimeFilter { get; set; }
        [NinjaScriptProperty] public bool FlatWhenOutside { get; set; }

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Name = "CleanNinjaBotIAMomentum";
                Calculate = Calculate.OnBarClose;
                Quantity = 1;
                StartHour = 9;
                StartMinute = 0;
                EndHour = 11;
                EndMinute = 0;
                Lb = 14;
                MacdFast = 9;
                MacdSlow = 48;
                MacdSignal = 11;
                StopLossTicks = 295;
                ProfitTargetTicks = 320;
                UseTimeFilter = true;
                FlatWhenOutside = true;
            }
            else if (State == State.Configure)
            {
                SetStopLoss(CalculationMode.Ticks, StopLossTicks);
                SetProfitTarget(CalculationMode.Ticks, ProfitTargetTicks);
            }
            else if (State == State.DataLoaded)
            {
                macdI = MACD(MacdFast, MacdSlow, MacdSignal);
            }
        }

        protected override void OnBarUpdate()
        {
            if (CurrentBar < MacdSlow + MacdSignal + 2)
                return;

            if (UseTimeFilter && !InSession())
            {
                if (FlatWhenOutside)
                    ExitIfOpen();
                return;
            }

            if (Position.MarketPosition == MarketPosition.Flat)
            {
                if (CrossAbove(macdI.Default, macdI.Avg, 1) && Close[0] > EMA(Lb)[0])
                    EnterLong(Quantity, "MomentumLong");
                else if (CrossBelow(macdI.Default, macdI.Avg, 1) && Close[0] < EMA(Lb)[0])
                    EnterShort(Quantity, "MomentumShort");
            }
            else if (Position.MarketPosition == MarketPosition.Long && CrossBelow(macdI.Default, macdI.Avg, 1))
                ExitLong("MomentumExitLong", "MomentumLong");
            else if (Position.MarketPosition == MarketPosition.Short && CrossAbove(macdI.Default, macdI.Avg, 1))
                ExitShort("MomentumExitShort", "MomentumShort");
        }

        private void ExitIfOpen()
        {
            if (Position.MarketPosition == MarketPosition.Long)
                ExitLong();
            else if (Position.MarketPosition == MarketPosition.Short)
                ExitShort();
        }

        private bool InSession()
        {
            var now = Time[0].Hour * 10000 + Time[0].Minute * 100 + Time[0].Second;
            return now >= StartHour * 10000 + StartMinute * 100 && now <= EndHour * 10000 + EndMinute * 100;
        }
    }

    public class CleanNinjaBotIARange : Strategy
    {
        private ATR atr;
        private EMA filter;
        private int state;

        [NinjaScriptProperty] public int contractSize { get; set; }
        [NinjaScriptProperty] public int StartHour { get; set; }
        [NinjaScriptProperty] public int StartMinute { get; set; }
        [NinjaScriptProperty] public int EndHour { get; set; }
        [NinjaScriptProperty] public int EndMinute { get; set; }
        [NinjaScriptProperty] public int SwingPeriod { get; set; }
        [NinjaScriptProperty] public double SwingMultiplier { get; set; }
        [NinjaScriptProperty] public double FilteATR { get; set; }
        [NinjaScriptProperty] public int ATRPeriod { get; set; }
        [NinjaScriptProperty] public double ATRMultiplierTP { get; set; }
        [NinjaScriptProperty] public double ATRMultiplierSL { get; set; }

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Name = "CleanNinjaBotIARange";
                Calculate = Calculate.OnBarClose;
                contractSize = 1;
                StartHour = 0;
                StartMinute = 0;
                EndHour = 12;
                EndMinute = 45;
                SwingPeriod = 15;
                SwingMultiplier = 4;
                FilteATR = 100;
                ATRPeriod = 12;
                ATRMultiplierTP = 3;
                ATRMultiplierSL = 3.5;
            }
            else if (State == State.DataLoaded)
            {
                atr = ATR(ATRPeriod);
                filter = EMA(SwingPeriod);
            }
        }

        protected override void OnBarUpdate()
        {
            if (CurrentBar < Math.Max(SwingPeriod, ATRPeriod) + 2)
                return;

            if (!InSession())
            {
                ExitIfOpen();
                return;
            }

            var band = atr[0] * SwingMultiplier;
            var newState = Close[0] > filter[0] + band ? 1 : Close[0] < filter[0] - band ? -1 : state;
            var changed = newState != 0 && newState != state;
            state = newState;

            if (Position.MarketPosition == MarketPosition.Flat)
            {
                if (changed && state > 0)
                    EnterLong(contractSize, "RangeLong");
                else if (changed && state < 0)
                    EnterShort(contractSize, "RangeShort");
                return;
            }

            var stopTicks = Math.Max(1, (int)Math.Round(atr[0] * ATRMultiplierSL / TickSize));
            var targetTicks = Math.Max(1, (int)Math.Round(atr[0] * ATRMultiplierTP / TickSize));
            SetStopLoss(CalculationMode.Ticks, stopTicks);
            SetProfitTarget(CalculationMode.Ticks, targetTicks);

            if (Position.MarketPosition == MarketPosition.Long && state < 0)
                ExitLong("RangeFlipLong", "RangeLong");
            else if (Position.MarketPosition == MarketPosition.Short && state > 0)
                ExitShort("RangeFlipShort", "RangeShort");
        }

        private void ExitIfOpen()
        {
            if (Position.MarketPosition == MarketPosition.Long)
                ExitLong();
            else if (Position.MarketPosition == MarketPosition.Short)
                ExitShort();
        }

        private bool InSession()
        {
            var now = Time[0].Hour * 10000 + Time[0].Minute * 100 + Time[0].Second;
            return now >= StartHour * 10000 + StartMinute * 100 && now <= EndHour * 10000 + EndMinute * 100;
        }
    }

    public class CleanNinjaBotIAOrbBreakout : Strategy
    {
        private double windowHigh;
        private double windowLow;
        private bool windowActive;
        private int tradesHoje;
        private DateTime tradeDate;

        [NinjaScriptProperty] public int LoteBase { get; set; }
        [NinjaScriptProperty] public int StartHour { get; set; }
        [NinjaScriptProperty] public int StartMinute { get; set; }
        [NinjaScriptProperty] public int EndHour { get; set; }
        [NinjaScriptProperty] public int EndMinute { get; set; }
        [NinjaScriptProperty] public int CloseAllHour { get; set; }
        [NinjaScriptProperty] public int CloseAllMinute { get; set; }
        [NinjaScriptProperty] public bool UsePartial { get; set; }
        [NinjaScriptProperty] public int Take1Ticks { get; set; }
        [NinjaScriptProperty] public int Take2Ticks { get; set; }
        [NinjaScriptProperty] public int StopLossTicks { get; set; }

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Name = "CleanNinjaBotIAOrbBreakout";
                Calculate = Calculate.OnBarClose;
                LoteBase = 1;
                StartHour = 8;
                StartMinute = 30;
                EndHour = 10;
                EndMinute = 0;
                CloseAllHour = 16;
                CloseAllMinute = 55;
                UsePartial = false;
                Take1Ticks = 135;
                Take2Ticks = 295;
                StopLossTicks = 105;
            }
            else if (State == State.Configure)
            {
                SetStopLoss(CalculationMode.Ticks, StopLossTicks);
                SetProfitTarget(CalculationMode.Ticks, UsePartial ? Take1Ticks : Take2Ticks);
            }
        }

        protected override void OnBarUpdate()
        {
            if (CurrentBar < 2)
                return;

            if (tradeDate != Time[0].Date)
            {
                tradeDate = Time[0].Date;
                tradesHoje = 0;
                windowActive = false;
                windowHigh = double.MinValue;
                windowLow = double.MaxValue;
            }

            if (ToHHmm(Time[0]) >= CloseAllHour * 100 + CloseAllMinute)
            {
                ExitIfOpen();
                return;
            }

            var now = ToHHmm(Time[0]);
            var start = StartHour * 100 + StartMinute;
            var end = EndHour * 100 + EndMinute;

            if (now >= start && now <= end)
            {
                windowActive = true;
                windowHigh = Math.Max(windowHigh, High[0]);
                windowLow = Math.Min(windowLow, Low[0]);
                return;
            }

            if (!windowActive || tradesHoje > 0 || Position.MarketPosition != MarketPosition.Flat)
                return;

            if (Close[0] > windowHigh)
            {
                tradesHoje++;
                EnterLong(LoteBase, "OrbBreakoutLong");
            }
            else if (Close[0] < windowLow)
            {
                tradesHoje++;
                EnterShort(LoteBase, "OrbBreakoutShort");
            }
        }

        private void ExitIfOpen()
        {
            if (Position.MarketPosition == MarketPosition.Long)
                ExitLong();
            else if (Position.MarketPosition == MarketPosition.Short)
                ExitShort();
        }

        private static int ToHHmm(DateTime time)
        {
            return time.Hour * 100 + time.Minute;
        }
    }

    public class CleanEmaSwingStrategy : Strategy
    {
        private EMA emaFast;
        private EMA emaSlow;
        private Swing swing;

        [NinjaScriptProperty] public int Stop { get; set; }
        [NinjaScriptProperty] public int Target { get; set; }

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Name = "CleanEmaSwingStrategy";
                Calculate = Calculate.OnBarClose;
                Stop = 100;
                Target = 160;
            }
            else if (State == State.Configure)
            {
                SetStopLoss(CalculationMode.Ticks, Stop);
                SetProfitTarget(CalculationMode.Ticks, Target);
            }
            else if (State == State.DataLoaded)
            {
                emaFast = EMA(9);
                emaSlow = EMA(21);
                swing = Swing(5);
            }
        }

        protected override void OnBarUpdate()
        {
            if (CurrentBar < 30)
                return;

            if (Position.MarketPosition == MarketPosition.Flat)
            {
                if (emaFast[0] > emaSlow[0] && Close[0] > swing.SwingHigh[0])
                    EnterLong(1, "EmaSwingLong");
                else if (emaFast[0] < emaSlow[0] && Close[0] < swing.SwingLow[0])
                    EnterShort(1, "EmaSwingShort");
            }
            else if (Position.MarketPosition == MarketPosition.Long && emaFast[0] < emaSlow[0])
                ExitLong("EmaSwingExitLong", "EmaSwingLong");
            else if (Position.MarketPosition == MarketPosition.Short && emaFast[0] > emaSlow[0])
                ExitShort("EmaSwingExitShort", "EmaSwingShort");
        }
    }
}
""";
}
